### ISSUE TITLE
[Chap2] p.125 연습문제 2번 attributeError 관련 질문입니다.

### ISSUE THREAD

**Issue by FleurHwai** [Ewha-Euron/Euron-DA-2021#16]
p.125 연습문제 2번에서 박하선님 노트북대로 코드를 실행했는데 계속 'AttributeError: 'GridSearchCV' object has no attribute 'best_params_' 이거나 'best_score_'이 없다는 에러가 떠요... 똑같이 코드를 써서 돌렸는데 뭐가 문제일까요,,, 아니면 정말 GridSearchCV에는 없는 attribute들인가요..??

**Comment by Also-yeon21** [comment]
안녕하세요, 하경님! 먼저 질문해주셔서 정말 감사드려요 :)

일단 말씀해주신 에러가 정확히 어떤 상황에서 발생한지 모르겠어요. 
저도 따라서 박하선님 코드를 돌려보았는데 크게 문제 없이 돌아가는 것 같아서... 
오류난 부분의 코드를 긁어와서 보여주시면 어떤 부분에 수정이 들어가야 하는지 확인하기가 더 좋을 것 같아요!

p.s. 제 추측으로는 fit 과정을 빠뜨리지는 않으셨는지 모르겠어요. 작성해주신 코드 앞뒤로 가져와주시면 다시 한 번 보겠습니다!

**Comment by FleurHwai** [comment]
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

param_distribs={'n_estimators':randint(low=1,high=200),
               'max_features':randint(low=1,high=8),}

forest_reg=RandomForestRegressor(random_state=42)
rnd_search=RandomizedSearchCV(forest_reg,param_distributions=param_distribs,
                              n_iter=10,cv=5,scoring='neg_mean_squared_error',random_state=42)
rnd_search.fit(housing_prepared,housing_labels)
cvres=rnd_search.cv_results_
for mean_score,params in zip(cvres["mean_test_score"],cvres["params"]):
    print(np.sqrt(-mean_score),params)

여깄습니다! fit을 했는데도 왜 그런지 모르겠네요..ㅜㅠㅠㅠ

**Comment by white-bean** [comment]
하경님! 늦게 답을 드려서 죄송합니다!!
일단 올려주신 코드를 보면 GridSearchCV의 best_params_를 뽑아보는 코드 자체가 없는 것 같은데 어디서 오류가 나는지 지금으로썬 저희가 확실하게 확인이 안돼요! 그리고 RandomizedSearchCV를 사용해서 튜닝을 하고 있는건데 왜 GridSearchCV의 오류가 나고 있는건지도 모르겠구요!
그리고 혹시나 해서 여쭤보는건데 코드는 하경님이 직접 작성하신건가요? 박하선님 노트북 상에 있는 코드랑 달라서요
이 답장 확인하시면 코드랑 오류나는 부분 전체 다 캡쳐해서 저희 데분팀 임원진이나 단톡방에 보내주시면 다시 확인해서 도움드리도록 하겠습니다!!!!
